<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE Countries [
	<!ELEMENT Countries (Country*) >
	<!ELEMENT Country (State*)>
	<!ATTLIST Country name CDATA  #REQUIRED >
	<!ATTLIST Country code CDATA  #REQUIRED >
	<!ELEMENT State EMPTY >
	<!ATTLIST State code CDATA #REQUIRED>
	<!ATTLIST State name CDATA #REQUIRED>
	<!ATTLIST State country IDREF #IMPLIED>
	<!ATTLIST State prefix CDATA #IMPLIED>
	<!ATTLIST State suffix CDATA #IMPLIED>
]>
<Countries>
	<Country code="USExtended" name="United States Extended">
		<State code="AA" name="Armed Forces (AA)" country="US"/>
		<State code="AE" name="Armed Forces (AE)" country="US"/>
		<State code="AP" name="Armed Forces (AP)" country="US"/>
		<State code="AL" name="Alabama" country="US"/>
		<State code="AK" name="Alaska" country="US"/>
		<State code="AS" name="American Samoa" country="US"/>
		<State code="AZ" name="Arizona" country="US"/>
		<State code="AR" name="Arkansas" country="US"/>
		<State code="FQ" name="Baker Island" country="US"/>
		<State code="CA" name="California" country="US"/>
		<State code="CO" name="Colorado" country="US"/>
		<State code="CT" name="Connecticut" country="US"/>
		<State code="DE" name="Delaware" country="US"/>
		<State code="DC" name="District of Columbia" country="US"/>
		<State code="FL" name="Florida" country="US"/>
		<State code="GA" name="Georgia" country="US"/>
		<State code="GU" name="Guam" country="US"/>
		<State code="HI" name="Hawaii" country="US"/>
		<State code="HQ" name="Howland Island" country="US"/>
		<State code="ID" name="Idaho" country="US"/>
		<State code="IL" name="Illinois" country="US"/>
		<State code="IN" name="Indiana" country="US"/>
		<State code="IA" name="Iowa" country="US"/>
		<State code="DQ" name="Jarvis Island" country="US"/>
		<State code="JQ" name="Johnston Atoll" country="US"/>
		<State code="KS" name="Kansas" country="US"/>
		<State code="KY" name="Kentucky" country="US"/>
		<State code="KQ" name="Kingman Reef" country="US"/>
		<State code="LA" name="Louisiana" country="US"/>
		<State code="ME" name="Maine" country="US"/>
		<State code="MH" name="Marshall Islands" country="US" prefix="U.S. Republic of"/>
		<State code="MD" name="Maryland" country="US"/>
		<State code="MA" name="Massachusetts" country="US"/>
		<State code="MI" name="Michigan" country="US"/>
		<State code="FM" name="Micronesia" country="US" prefix="Federated States of"/>
		<State code="MQ" name="Midway Islands" country="US"/>
		<State code="MN" name="Minnesota" country="US"/>
		<State code="MS" name="Mississippi" country="US"/>
		<State code="MO" name="Missouri" country="US"/>
		<State code="MT" name="Montana" country="US"/>
		<State code="NE" name="Nebraska" country="US"/>
		<State code="NV" name="Nevada" country="US"/>
		<State code="BQ" name="Navassa Island" country="US"/>
		<State code="MP" name="Northern Mariana Islands" country="US"/>
		<State code="NH" name="New Hampshire" country="US"/>
		<State code="NJ" name="New Jersey" country="US"/>
		<State code="NM" name="New Mexico" country="US"/>
		<State code="NY" name="New York" country="US"/>
		<State code="NC" name="North Carolina" country="US"/>
		<State code="ND" name="North Dakota" country="US"/>
		<State code="OH" name="Ohio" country="US"/>
		<State code="OK" name="Oklahoma" country="US"/>
		<State code="OR" name="Oregon" country="US"/>
		<State code="LQ" name="Palmyra Atoll" country="US"/>
		<State code="PA" name="Pennsylvania" country="US"/>
		<State code="PW" name="Palau" country="US" prefix="Republic of"/>
		<State code="PR" name="Puerto Rico" country="US" prefix="Commonwealth of"/>
		<State code="RI" name="Rhode Island" country="US"/>
		<State code="SC" name="South Carolina" country="US"/>
		<State code="SD" name="South Dakota" country="US"/>
		<State code="TN" name="Tennessee" country="US"/>
		<State code="TX" name="Texas" country="US"/>
		<State code="UT" name="Utah" country="US"/>
		<State code="VT" name="Vermont" country="US"/>
		<State code="VA" name="Virginia" country="US"/>
		<State code="VI" name="Virgin Islands" country="US" prefix="U.S."/>
		<State code="WA" name="Washington" country="US"/>
		<State code="WQ" name="Wake Island" country="US"/>
		<State code="WV" name="West Virginia" country="US"/>
		<State code="WI" name="Wisconsin" country="US"/>
		<State code="WY" name="Wyoming" country="US"/>
	</Country>
	<Country code="US" name="United States">
		<State code="AL" name="Alabama" country="US"/>
		<State code="AK" name="Alaska" country="US"/>
		<State code="AZ" name="Arizona" country="US"/>
		<State code="AR" name="Arkansas" country="US"/>
		<State code="CA" name="California" country="US"/>
		<State code="CO" name="Colorado" country="US"/>
		<State code="CT" name="Connecticut" country="US"/>
		<State code="DE" name="Delaware" country="US"/>
		<State code="DC" name="District of Columbia" country="US"/>
		<State code="FL" name="Florida" country="US"/>
		<State code="GA" name="Georgia" country="US"/>
		<State code="HI" name="Hawaii" country="US"/>
		<State code="ID" name="Idaho" country="US"/>
		<State code="IL" name="Illinois" country="US"/>
		<State code="IN" name="Indiana" country="US"/>
		<State code="IA" name="Iowa" country="US"/>
		<State code="KS" name="Kansas" country="US"/>
		<State code="KY" name="Kentucky" country="US"/>
		<State code="LA" name="Louisiana" country="US"/>
		<State code="ME" name="Maine" country="US"/>
		<State code="MD" name="Maryland" country="US"/>
		<State code="MA" name="Massachusetts" country="US"/>
		<State code="MI" name="Michigan" country="US"/>
		<State code="MN" name="Minnesota" country="US"/>
		<State code="MS" name="Mississippi" country="US"/>
		<State code="MO" name="Missouri" country="US"/>
		<State code="MT" name="Montana" country="US"/>
		<State code="NE" name="Nebraska" country="US"/>
		<State code="NV" name="Nevada" country="US"/>
		<State code="NH" name="New Hampshire" country="US"/>
		<State code="NJ" name="New Jersey" country="US"/>
		<State code="NM" name="New Mexico" country="US"/>
		<State code="NY" name="New York" country="US"/>
		<State code="NC" name="North Carolina" country="US"/>
		<State code="ND" name="North Dakota" country="US"/>
		<State code="OH" name="Ohio" country="US"/>
		<State code="OK" name="Oklahoma" country="US"/>
		<State code="OR" name="Oregon" country="US"/>
		<State code="PA" name="Pennsylvania" country="US"/>
		<State code="RI" name="Rhode Island" country="US"/>
		<State code="SC" name="South Carolina" country="US"/>
		<State code="SD" name="South Dakota" country="US"/>
		<State code="TN" name="Tennessee" country="US"/>
		<State code="TX" name="Texas" country="US"/>
		<State code="UT" name="Utah" country="US"/>
		<State code="VT" name="Vermont" country="US"/>
		<State code="VA" name="Virginia" country="US"/>
		<State code="WA" name="Washington" country="US"/>
		<State code="WV" name="West Virginia" country="US"/>
		<State code="WI" name="Wisconsin" country="US"/>
		<State code="WY" name="Wyoming" country="US"/>
	</Country>
	<Country code="CA" name="Canada" >
		<State code="AB" name="Alberta" country="CA"/>
		<State code="BC" name="British Columbia" country="CA"/>
		<State code="MB" name="Manitoba" country="CA"/>
		<State code="NB" name="New Brunswick" country="CA"/>
		<State code="NL" name="Newfoundland" country="CA" suffix="and Labrador"/>
		<State code="NS" name="Nova Scotia" country="CA"/>
		<State code="NT" name="Northwest Territories" country="CA"/>
		<State code="NU" name="Nunavut" country="CA"/>
		<State code="ON" name="Ontario" country="CA"/>
		<State code="PE" name="Prince Edward Island" country="CA"/>
		<State code="QC" name="Quebec" country="CA"/>
		<State code="SK" name="Saskatchewan" country="CA"/>
		<State code="YK" name="Yukon" country="CA"/>
	</Country>
	<Country code="GB" name="Great Brittian" >
		<State code="EN" name="England" country="GB"/>
		<State code="NB" name="Northern Ireland" country="GB"/>
		<State code="SF" name="Scotland" country="GB"/>
		<State code="WL" name="Wales" country="GB"/>
		<State code="VG" name="Virgin Islands" country="GB" prefix="G.B."/>
	</Country>
	<Country name="France" code="FR" >
		<State code="GF" name="French Guiana" country="FR"/>
		<State code="PF" name="French Polynesia" country="FR"/>
	</Country>
	<Country name="Netherlands" code="NL" >
		<State code="AN" name="Netherlands Antilles" country="NL"/>
	</Country>
</Countries>